version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_media: {}
  production_static: {}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    volumes:
      - production_media:/data/media
      - production_static:/data/static

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
    env_file:
      - ./.envs/.production/.nginx
    networks:
      traefik:
        aliases:
          - {{ cookiecutter.project_slug }}_nginx
      default:
        aliases:
          - nginx
    ports:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.backend={{ cookiecutter.project_slug }}_nginx
      - traefik.frontend.rule=Host:{{cookiecutter.domain_name}}
      - traefik.docker.network=traefik
      - traefik.port=80
      - traefik.protocol=http
    volumes:
      - production_media:/data/media
      - production_static:/data/static

  redis:
    image: redis:3.2

  redis:
    image: redis:3.2
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_flower
    ports:
      - "5555:5555"
    command: /start-flower

  {%- endif %}

networks:
  traefik:
    external: true
